<a href="https://colab.research.google.com/github/lotusist/Basics-of-Mathmatics-and-Statistics/blob/main/introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Basics

In [ ]:
import numpy as np

#### Array를 활용한 행렬 만들기

In [ ]:
x = np.array([[1,2,3,4,5], [1,2,3,4,5]])

In [ ]:
x

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [ ]:
x.shape

(2, 5)

In [ ]:
type(x)

numpy.ndarray

In [ ]:
X = np.arange(20)

In [ ]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
X[0]

0

In [ ]:
X[0] = 20

In [ ]:
X

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 0으로만 이루어진 행렬 생성

In [ ]:
X = np.zeros((5,5))

In [ ]:
X

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
X.shape

(5, 5)

#### 동일한 원소로 구성된 행렬 생성

In [ ]:
X = np.full((3,3), 22)

In [ ]:
X

array([[22, 22, 22],
       [22, 22, 22],
       [22, 22, 22]])

#### Reshape를 활용한 행렬 생성

In [ ]:
X = np.arange(20).reshape((4,5))
print(X)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


#### Dot Product (행렬간 곱셈)

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7], [8,9,10]])
ab = np.dot(a,b)

In [ ]:
print(a)
print(b)
print(ab)

[[1 2]
 [3 4]]
[[ 5  6  7]
 [ 8  9 10]]
[[21 24 27]
 [47 54 61]]


#### Matrix를 활용한 행렬 생성

In [ ]:
a = np.matrix([[1,2], [3,4]])
b = np.matrix([[5,6,7], [8,9,10]])
ab = np.dot(a,b)
ab2 = a*b

print(ab)
print(ab2)

[[21 24 27]
 [47 54 61]]
[[21 24 27]
 [47 54 61]]


#### 대각행렬의 생성


In [ ]:
x1 = np.arange(1,5)
x1_diag = np.diag(x1)

print(x1)
print(x1_diag)

[1 2 3 4]
[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 항등행렬의 생성

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 행렬간 결합 구성하기

In [ ]:
np.vstack([ab, ab2])

matrix([[21, 24, 27],
        [47, 54, 61],
        [21, 24, 27],
        [47, 54, 61]])

#### 행렬 전치

In [ ]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6,7], [8,9,10]])

abt1 = np.dot(a,b).T
abt2 = np.dot(b.T, a.T)
print (abt1)
print(abt2)

[[21 47]
 [24 54]
 [27 61]]
[[21 47]
 [24 54]
 [27 61]]


#### 역행렬

In [ ]:
a_inv = np.linalg.inv(a)
print(a_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


#### Exercise

- Exercise 3.6. in MATHMATICS FOR MACHINE LEARNING (M. P. Deisenroth et al. )

In [ ]:
B = np.array([[0,1,-3],[-1,-3,4],[2,1,1],[0,-1,2],[2,2,1]])
x = np.array([-1,-9,-1,4,1]).T

In [ ]:
temp1 = np.dot(B.T, B)
temp2 = np.linalg.inv(temp1)
lambda_ = np.dot(np.dot(temp2, B.T), x)
print(lambda_)

[-3.  4.  1.]


In [ ]:
result_a = np.dot(B, lambda_)
result_a

array([ 1., -5., -1., -2.,  3.])

In [ ]:
square_list = []
for i in range(len(x)):
  square_list.append((x[i]-result_a[i])**2)
temp_result_b = sum(square_list)

In [ ]:
import math
result_b = math.sqrt(temp_result_b)
result_b

7.745966692414833